### ISSUE TITLE
完整代码？

### ISSUE THREAD

**Issue by kaigelee** [WangChangqi98/CSS#1]
请问完整代码什么时候放出?

**Comment by WangChangqi98** [comment]
完整代码预计等iccv camera ready的deadline（8.13）前后放出，届时将更新两个新的数据集接口以及一些可视化相关的代码

**Comment by kaigelee** [comment]
> 完整代码预计等iccv camera ready的deadline（8.13）前后放出，届时将更新两个新的数据集接口以及一些可视化相关的代码

           想问一下Model_mix中，代码pseudo_labels = pseudo_labels_cls - label_mask * self.num_classes ，因为pseudo_labels_cls 一般是【0,num_classes-1】，这样不会把 pseudo_labels全部变为负数嘛？    后续在执行：pseudo_labels[pseudo_labels < 0] = 255；会把所有伪标签都变为255吧？

**Comment by WangChangqi98** [comment]
并不会全部变成255，因为label mask 是0，1的一个bool型的mask，并不是所有地方都会是1，我们这么做就是要让rep space和logit space上不一样的预测不计算在loss内，255在后续loss计算中会被忽略。
