### ISSUE TITLE
About the split

### ISSUE THREAD

**Issue by Hugo-cell111** [WangChangqi98/CSS#10]
Hi! Could you please provide txt files of the labeled and unlabeled data split? Thanks!

**Comment by WangChangqi98** [comment]
They are the same with those in U2PL, you can download them from their repo. Or I will update data split tomorrow, I am not available with my server now, sorry.

**Comment by Hugo-cell111** [comment]
Don't worry about it, I will go to their repo. Thanks!

**Comment by Hugo-cell111** [comment]
Hi! Sorry to reopen the issue. You say you use the same split as U2PL, since many works such as UniMatch, iMAS, AugSeg find the split used in U2PL is unfair and reproduce U2PL, have you tried to reproduce your work with the split from UniMatch? Using the split from UniMatch will naturally boost the mIOU performance. Thanks!

**Comment by WangChangqi98** [comment]
Sorry for my late reply! UniMatch and AugSeg are published in CVPR 2023 (released in March), so I have not read them when I submitted my paper to ICCV (8th March). I did not consider a lot about the split in this work, and I simply follow the U2PL.
By the way, I think it is not very essential to over consider the choice of split, the motivation of your work and the ablations are more important. If you have enough time and computing resources, you can try to use different splits when compared to different SOTA approaches. It is more fair. However, if you have difficulty to do that, I think it is OK to use the split which can achieve best performance.

**Comment by Hugo-cell111** [comment]
Yes, you are right! Plus in your work you don't compare those who use different splits as U2PL, so your comparison towards the baseline is fair and correct. Anyway, I have no more doubt. Thank you for your answer!
