### ISSUE TITLE
Ask for the training logs

### ISSUE THREAD

**Issue by Hugo-cell111** [WangChangqi98/CSS#12]
Hi! Could you provide the complete training logs of your work? And may I ask how many GPUs with how much memory are required in your work? Thanks a lot!

**Comment by WangChangqi98** [comment]
I'm sorry I cannot provide it for you now. I need to use school network to log in my server, but I am at home now. I will go back to school tomorrow and download the log. However, my log only records the mIoU in each epoch and the current time, will it help you?
In regard to GPU and memory, I use 4 A5000 (24G) to train the model on VOC 2012, batch size is 4 per GPU, and total 16, over 12G but less 16G memory capacity is needed per GPU. As for Cityscapes, I use 1 A100 (80G) and batch size is 8. I can not see the memory used on A100. However, I have tried to train my model with 4 A5000 in DDP mode, the batch size is 2 and 20G is needed per GPU.

**Comment by Hugo-cell111** [comment]
Don't worry, take your time! Just recording the mIOU has already helped me a lot. Thank you!
