### ISSUE TITLE
Question about the indicator

### ISSUE THREAD

**Issue by Hugo-cell111** [WangChangqi98/CSS#13]
Hi! Have you tried directly using the consistent prediction between two kinds of classifiers without applying the indicator (which can be found in the [code](https://github.com/WangChangqi98/CSS/blob/main/generalframeworks/loss/loss.py#L56). I conduct the experiment and find the performance drops rapidly. And I wonder whether the threshold or the mixing-labels strategy truly works and contributes more to the final performance. Thanks!

**Comment by WangChangqi98** [comment]
Sorry I cannot understand the meaning of consistent prediction, does it means the same part of the prediction in the logit and representation space? This prediction need to be filtered by some approaches. If not it is not very reliable and will hurt the unsupervised training process. So the threshold and indicator is important. Similar conclusion can be found in ReCo.

**Comment by Hugo-cell111** [comment]
Yes, you totally get my point. Thanks a lot@

**Comment by Hugo-cell111** [comment]
Yes, you totally get my point. Thanks a lot!
