### ISSUE TITLE
About the email

### ISSUE THREAD

**Issue by Hugo-cell111** [WangChangqi98/CSS#15]
Hello! May I ask what your frequently used email address is? I have some questions about the fusion of predictions in the rep space and logit space and I hope I can discuss with you. I wonder if it's convenient for you. Thanks!

**Comment by WangChangqi98** [comment]
I think WeChat is more convenient. My WeChat is w1448450041, my email is wangchangqi98@gmail.com.

**Comment by Hugo-cell111** [comment]
Thanks a lot!
