### ISSUE TITLE
关于indicator的作用

### ISSUE THREAD

**Issue by CannotBeFatAnyMore** [WangChangqi98/CSS#17]
您好！ 感谢您的卓越工作，在拜读您的作品时，我有一些困惑：在3.4. Training Objective一节中,representation space采样策略分为三个部分：1）Valid sampling Strategy，2）Hard Sampling Strategy，3）Negative Sampling Strategy 
通过这些策略采样的样本是怎么使用的？我在论文和代码中好像没有找到相应的描述，可以帮我指出吗？

**Comment by WangChangqi98** [comment]
您好！我们的采样策略与同类的工作ReCo相似，通过采样策略的样本会直接应用到对比学习中，没有通过的representation则会被直接抛弃。

**Comment by WangChangqi98** [comment]
也就是说用于对比学习的anchor, negative keys都是通过采样策略获得的，positive keys则是prototype

**Comment by CannotBeFatAnyMore** [comment]
> 您好！我们的采样策略与同类的工作ReCo相似，通过采样策略的样本会直接应用到对比学习中，没有通过的representation则会被直接抛弃。

感谢您的回复，只是还有一个细节不是很明确，请赐教！
基于此，Negative Sampling Strategy 采样的为负样本，另外两个策略采样得到的是正样本吗？

**Comment by WangChangqi98** [comment]
不是的，采样的锚点(anchor)或者是负样本他们都必须先满足valid sampling strategy，也就是说confidence或者similarity必须先高于某一个值，然后才会被考虑作为锚点或者是负样本，至于正样本(positive keys)我们这里用的是prototype来代替的，很多同类的文章也是这么处理，当然也可以用采样的方式，只不过我们没用。

**Comment by CannotBeFatAnyMore** [comment]
好的！ 谢谢，我明白了
