### ISSUE TITLE
Question about the loss

### ISSUE THREAD

**Issue by Hugo-cell111** [WangChangqi98/CSS#3]
Hi! I wonder why the supervised loss function is CE Loss when the dataset is Pascal VOC while the function is ProbOhemCrossEntropy2d when the dataset is the other one (such as Cityscapes and COCO)? Thanks!

**Comment by WangChangqi98** [comment]
Hi, this is because the ProbOhemCrossEntropy2d can achieve better performance especially on Cityscapes. Meanwhile, the SOTAs which we compared with are also adopted ProbOhemCrossEntropy2d on Cityscapes, so for a fair comparison, we need to use it.

**Comment by Hugo-cell111** [comment]
Yes, I know the ProbOhemCrossEntropy2d is always used in the previous works. Do you mean even using the normal CE Loss will achieve the best performance, so the ProbOhemCrossEntropy2d is not needed in VOC?

**Comment by WangChangqi98** [comment]
Yes, I think so, ProbOhemCrossEntropy2d may be used to find more hard pixels but in VOC, CE may be enough to reach the convinced performance.

**Comment by WangChangqi98** [comment]
Unfortunately we did not try to apply ProbOhemCrossEntropy2d on VOC, and this may be a good try to see whether ProbOhemCrossEntropy2d can achieve better performance or not.

**Comment by Hugo-cell111** [comment]
Thanks!
