### ISSUE TITLE
Question about the contrastive loss

### ISSUE THREAD

**Issue by Hugo-cell111** [WangChangqi98/CSS#8]
Hi! What is the difference between Contrast_Loss_ds and Contrast_Loss? Plus may you provide the training log of the experiment? I want to see the convergence curve of contrastive loss. Thanks a lot!

**Comment by WangChangqi98** [comment]
Hi, I'm sorry, the Contrast_Loss_ds was used in the middle of our research and it is not used now! We wanted to try a Dynamic Strong (ds) threshold at first, so we write this function, you can see that strong threshold in this function can be changed during the training process, not always a fixed value in __init__().

I am afraid that I could not find the log of the contrastive loss, but I remember the loss converged normally, but the final value was much larger than the value of supervised and unsupervised loss, about 10 times larger.

**Comment by Hugo-cell111** [comment]
Thank you for your immediate response! You say "converge normally", do you remember how much the initial loss value and the final loss value are? I want to raise this question because when I apply my own contrastive loss, the loss value drops very slightly, about from 3.6 to 3.58 even after hundreds of epochs. Plus, my contrastive loss is also about 10 times larger other terms of loss.

**Comment by WangChangqi98** [comment]
yes, I think it is a normal phenomenon, my contrastive loss also dropped slightly. Meanwhile, I had run the ReCo (a paper published in ICLR 2022) before, the contrastive loss also declined slightly. By the way, our code is highly derived from ReCo actually (lol).

**Comment by Hugo-cell111** [comment]
Thank you very much! Quite solve my problem very well. Thanks again!

**Comment by WangChangqi98** [comment]
You are welcome and happy national day! 😊
