### ISSUE TITLE
Question about the ablation study of contrastive loss

### ISSUE THREAD

**Issue by Hugo-cell111** [WangChangqi98/CSS#9]
Hi! Have you conducted the ablation study of contrastive loss? I haven't seen any relative experiments in the paper and I wonder the contribution to the performance of this component.

**Comment by WangChangqi98** [comment]
We conducted the experiments about CutMix method, the difference between our method and CutMix is L_c, so we think contrastive loss has contribution to final performance.
In addition, I had run simple contrastive-based teacher student framework before, and it also contributed to final performance.

**Comment by Hugo-cell111** [comment]
Thanks!
